module.exports = {
    OK_STATUS: 'OK',
    HELP_STATUS: 'HELP',
    EMERGENCY_STATUS: 'EMERGENCY',
    UNDEFINED_STATUS: 'UNDEFINED',
    PAGINATION_NUMBER: 10,
    MESSAGE_LEVEL_SPAM: 'message',
    MESSAGE_SPAM_REPORTED_LIMIT: 3,
    USER_LEVEL_SPAM: 'user',
    USER_SPAM_REPORTED_LIMIT: 5
};
